### ISSUE TITLE
Submit to npm

### ISSUE THREAD

**Issue by colinodell** [colinodell/tunegenie-spotify#6]
This needs a lot of work before that can happen:
- [ ] #1 - Fully implement OAuth2
- [ ] #4 - Better error handling
- [ ] #5 - Test/fix the bin script

I may also want to address #2 and #3 so it's more decoupled and more useful too.
